pipeline{
    agent any
    options{
        timestamps()
    }
    environment{
        buildID = "$BUILD_ID"
    }
    stages{
        stage('Build Docker Image'){
            steps{
                echo "Buld docker images for GuessNum python application..."
                script{
                    sh "docker build -t sandeepb3245/guessnumpy:$buildID -f /guess-numapp ."
                }
                post{
                    success{
                        echo "Docker image build successfully. "
                    }
                }
            }
        }
    }
}