pipeline{
    agent any
    options{
        timestamps()
    }
    environment{
        buildID = "$BUILD_ID"
    }
    stages{
        stage('Build Docker Image'){
            steps{
                echo "Buld docker images for GuessNum python application..."
                script{
                    sh "docker build -f ./guess-numapp/Dockerfile . -t sandeepb3245/guessnumpy:$buildID "
                }
            }
            post{
                success{
                    echo "Docker image created successfully with build number: $buildID "
                }
            }
        }
    }
}